jobs:
  CLAAssistant:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.ZAP_CLA_PAT }}
      if: (github.event.comment.body == 'recheck' || github.event.comment.body ==
        'I have read the CLA Document and I hereby sign the CLA') || github.event_name
        == 'pull_request_target'
      name: CLA Assistant
      uses: contributor-assistant/github-action@v2.3.0
      with:
        allowlist: zapbot,dependabot
        branch: main
        path-to-document: https://github.com/zaproxy/zaproxy/blob/main/CLA.md
        path-to-signatures: signatures/version1/cla.json
        remote-organization-name: zaproxy
        remote-repository-name: cla
name: CLA Assistant
on:
  repository_dispatch:
    types: trigger-ga___cla.yml
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
