jobs:
  handle-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        CROWDIN_AUTH_TOKEN: ${{ secrets.ZAPBOT_CROWDIN_TOKEN }}
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
      name: Handle Release
      run: ./gradlew handleReleaseFromGitHubRef
name: Handle Release
on:
  repository_dispatch:
    types: trigger-ga___handle-release.yml
