jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: join(github.event.pull_request.labels) == ''
      uses: actions/labeler@v4
      with:
        configuration-path: .github/workflows/conf/pr-labeler.yml
        dot: true
name: Pull Request Labeler
on:
  repository_dispatch:
    types: trigger-ga___pr-labeler.yml
