jobs:
  prepare-release:
    name: Prepare Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Prepare Release
      run: ./gradlew :zap:prepareMainRelease
    - continue-on-error: true
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
      name: Create Pull Request
      run: ./gradlew :zap:createPullRequestMainRelease
name: Prepare Release Main Version
on:
  repository_dispatch:
    types: trigger-ga___prepare-release-main-version.yml
