jobs:
  publish:
    name: Build and Push Docker Images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      run: 'sudo apt-get install xmlstarlet

        echo "REL_VERSION=$(curl -s https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml
        | xmlstarlet sel -t -v //core/version)" >> $GITHUB_ENV

        echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV

        echo "REL_DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Set up Chalk
      uses: crashappsec/setup-chalk-action@main
      with:
        password: ${{ secrets.CHALK_PASSWORD }}
        private_key: ${{ secrets.CHALK_PRIVATE_KEY }}
        public_key: ${{ secrets.CHALK_PUBLIC_KEY }}
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
        username: zapbot
    - continue-on-error: true
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Build and push stable Docker image
      uses: docker/build-push-action@v5
      with:
        annotations: "index:org.opencontainers.image.source=https://github.com/zaproxy/zaproxy\n\
          index:org.opencontainers.image.description=The stable Docker image for the\
          \ world\u2019s most widely used web app scanner.\nindex:org.opencontainers.image.licenses=Apache-2.0\n"
        context: docker
        file: docker/Dockerfile-stable
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: false
        secrets: 'webswing_url=${{ secrets.WEBSWING_URL }}

          '
        tags: 'ghcr.io/zaproxy/zaproxy:${{ env.REL_DATE_SHORT }}-stable

          ghcr.io/zaproxy/zaproxy:${{ env.REL_VERSION }}

          ghcr.io/zaproxy/zaproxy:stable

          ghcr.io/zaproxy/zaproxy:latest

          softwaresecurityproject/zap-stable:${{ env.REL_DATE_SHORT }}

          softwaresecurityproject/zap-stable:${{ env.REL_VERSION }}

          softwaresecurityproject/zap-stable:latest

          zaproxy/zap-stable:${{ env.REL_DATE_SHORT }}

          zaproxy/zap-stable:${{ env.REL_VERSION }}

          zaproxy/zap-stable:latest

          '
    - continue-on-error: true
      name: Build and push bare Docker image
      uses: docker/build-push-action@v5
      with:
        annotations: "org.opencontainers.image.source=https://github.com/zaproxy/zaproxy\n\
          org.opencontainers.image.description=The bare Docker image for the world\u2019\
          s most widely used web app scanner.\norg.opencontainers.image.licenses=Apache-2.0\n"
        context: docker
        file: docker/Dockerfile-bare
        platforms: linux/amd64
        provenance: false
        push: false
        tags: 'ghcr.io/zaproxy/zaproxy:${{ env.REL_DATE_SHORT }}-bare

          ghcr.io/zaproxy/zaproxy:${{ env.REL_VERSION }}-bare

          ghcr.io/zaproxy/zaproxy:bare

          softwaresecurityproject/zap-bare:${{ env.REL_DATE_SHORT }}

          softwaresecurityproject/zap-bare:${{ env.REL_VERSION }}

          softwaresecurityproject/zap-bare:latest

          zaproxy/zap-bare:${{ env.REL_DATE_SHORT }}

          zaproxy/zap-bare:${{ env.REL_VERSION }}

          zaproxy/zap-bare:latest

          '
name: Release Main Docker
on:
  repository_dispatch:
    types: trigger-ga___release-main-docker.yml
