jobs:
  release:
    name: Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: build
      uses: snapcore/action-build@v1
      with:
        path: snap
    - continue-on-error: true
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.ZAPBOT_SNAP_STORE_LOGIN }}
      uses: snapcore/action-publish@v1
      with:
        release: stable
        snap: ${{ steps.build.outputs.snap }}
name: Release Snap
on:
  repository_dispatch:
    types: trigger-ga___release-snap.yml
