jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      run: 'echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV

        echo "REL_DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Set up Chalk
      uses: crashappsec/setup-chalk-action@main
      with:
        password: ${{ secrets.CHALK_PASSWORD }}
        private_key: ${{ secrets.CHALK_PRIVATE_KEY }}
        public_key: ${{ secrets.CHALK_PUBLIC_KEY }}
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
        username: zapbot
    - continue-on-error: true
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        annotations: "index:org.opencontainers.image.source=https://github.com/zaproxy/zaproxy\n\
          index:org.opencontainers.image.description=The weekly Docker image for the\
          \ world\u2019s most widely used web app scanner.\nindex:org.opencontainers.image.licenses=Apache-2.0\n"
        context: docker
        file: docker/Dockerfile-weekly
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: false
        secrets: 'webswing_url=${{ secrets.WEBSWING_URL }}

          '
        tags: 'ghcr.io/zaproxy/zaproxy:${{ env.REL_DATE_SHORT }}-weekly

          ghcr.io/zaproxy/zaproxy:weekly

          softwaresecurityproject/zap-weekly:${{ env.REL_DATE_SHORT }}

          softwaresecurityproject/zap-weekly:latest

          zaproxy/zap-weekly:${{ env.REL_DATE_SHORT }}

          zaproxy/zap-weekly:latest

          '
name: Release Weekly Docker
on:
  repository_dispatch:
    types: trigger-ga___release-weekly-docker.yml
