jobs:
  release:
    name: Build and Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
        ZAP_JAVA_VERSION: 11
        ZAP_RELEASE: 1
      name: Build and Release
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g :zap:createMainRelease
  upload-macos:
    name: Build and Upload macOS Dist
    needs: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
        ZAP_JAVA_VERSION: 11
        ZAP_RELEASE: 1
      name: Build and Upload
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g :zap:uploadMacDist
name: Release Main Version
on:
  repository_dispatch:
    types: trigger-ga___release-main-version.yml
