jobs:
  publish:
    name: Build, Push and Run Docker Image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        annotations: 'index:org.opencontainers.image.source=https://github.com/zaproxy/zaproxy

          index:org.opencontainers.image.description=Docker image used for ZAP integration
          tests.

          index:org.opencontainers.image.licenses=Apache-2.0

          '
        context: docker
        file: docker/Dockerfile-tests
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: false
        secrets: 'webswing_url=${{ secrets.WEBSWING_URL }}

          '
        tags: 'ghcr.io/zaproxy/zaproxy-tests

          '
    - continue-on-error: true
      name: Run install tests
      run: docker run --rm -t ghcr.io/zaproxy/zaproxy-tests wrk/install_tests.sh
    - continue-on-error: true
      name: Run python tests
      run: docker run --rm -t ghcr.io/zaproxy/zaproxy-tests wrk/python_tests.sh
    - continue-on-error: true
      name: Automation Framework context tests
      run: docker run --rm -t ghcr.io/zaproxy/zaproxy-tests wrk/af_context_tests.sh
    - continue-on-error: true
      name: Automation Framework plan tests
      run: docker run --rm -t ghcr.io/zaproxy/zaproxy-tests wrk/af_plan_tests.sh
    - continue-on-error: true
      name: Run baseline tests
      run: docker run --rm -t ghcr.io/zaproxy/zaproxy-tests wrk/baseline_tests.sh
name: Build and Run Integration Tests Docker
on:
  repository_dispatch:
    types: trigger-ga___run-integration-tests.yml
