jobs:
  sonar:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Gradle Test & Coverage Report
      run: ./gradlew test jacocoTestReport -Dorg.gradle.jvmargs=-Xmx4096m
    - continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.ZAPBOT_SONARCLOUD_TOKEN }}
      name: Sonarcloud Scan
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g sonar --stacktrace
name: Run Sonar
on:
  repository_dispatch:
    types: trigger-ga___sonar.yml
